---
version: '3.8'


services:
  zookeeper:
    image: debezium/zookeeper:1.5.0.Final
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"


  kafka:
    image: debezium/kafka:1.5.0.Final
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_HOME: "/kafka"
      BOOTSTRAP_SERVER: "kafka:9092"
      ZOOKEEPER_CONNECT: 'zookeeper:2181'
  registry:
    image: confluentinc/cp-schema-registry:6.0.2
    hostname: registry
    container_name: registry
    depends_on:
      - zookeeper
      - kafka
    ports:
      - 8081:8081
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka:9092
      SCHEMA_REGISTRY_HOST_NAME: registry

  gui:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - CUSTOM_CRT_URL=http://pki.jlab.org/JLabCA.crt
    tty: true
    stdin_open: true
    hostname: gui
    container_name: gui
    depends_on:
      - kafka
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      SCHEMA_REGISTRY: http://registry:8081
      DISPLAY: ${DOCKER_DISPLAY}
    volumes:
      - ./scripts:/scripts
    entrypoint: bash

  jaws:
    image: slominskir/jaws:2.6.1
    tty: true
    stdin_open: true
    hostname: jaws
    container_name: jaws
    depends_on:
      - zookeeper
      - kafka
      - registry
    environment:
      BOOTSTRAP_SERVERS: "kafka:9092"
      SCHEMA_REGISTRY: "http://registry:8081"
      ALARM_DEFINITIONS: "alarm1|channel1|INJ|RF|/,alarm2|channel2|INJ|RF|/,alarm3|channel3|INJ|RF|/"
  
  state:
    image: slominskir/alarm-state-processor:1.1.0
    hostname: state
    container_name: state
    depends_on:
      - zookeeper
      - kafka
      - registry
      - jaws
    environment:
      BOOTSTRAP_SERVERS: "kafka:9092"
      SCHEMA_REGISTRY: "http://registry:8081"
   
  auto:
    image: slominskir/jaws-auto-override-processor:1.4.0
    hostname: auto
    container_name: auto
    depends_on:
      - zookeeper
      - kafka
      - registry
      - jaws
    environment:
      BOOTSTRAP_SERVERS: "kafka:9092"
      SCHEMA_REGISTRY: "http://registry:8081"
      
   