---
version: '3.8'

networks:
  graphnet:
    name: 'graphical-net'

services:
  zookeeper:
    image: debezium/zookeeper:1.4.0.Final
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - graphnet

  kafka:
    image: debezium/kafka:1.4.0.Final
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_HOME: "/kafka"
      BOOTSTRAP_SERVER: "kafka:9092"
      ZOOKEEPER_CONNECT: 'zookeeper:2181'
      CREATE_TOPICS: 'registered-alarms:1:1:compact,active-alarms:1:1:compact,shelved-alarms:1:1:compact'
    networks:
      - graphnet

  registry:
    image: confluentinc/cp-schema-registry:6.0.1
    hostname: registry
    container_name: registry
    depends_on:
      - zookeeper
      - kafka
    ports:
      - 8081:8081
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka:9092
      SCHEMA_REGISTRY_HOST_NAME: registry
    networks:
      - graphnet

  console:
    image: slominskir/kafka-alarm-system:1.3.1
    tty: true
    stdin_open: true
    hostname: console
    container_name: console
    depends_on:
      - zookeeper
      - kafka
      - registry
    environment:
      BOOTSTRAP_SERVERS: "kafka:9092"
      SCHEMA_REGISTRY: "http://registry:8081"
      ALARM_DEFINITIONS: "alarm1|channel1|INJ|RF|/|/,alarm2|channel2|INJ|RF|/|/,alarm3|channel3|INJ|RF|/|/"
    networks:
      - graphnet

  gui:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - CUSTOM_CRT_URL=http://pki.jlab.org/JLabCA.crt
    tty: true
    stdin_open: true
    hostname: gui
    container_name: gui
    depends_on:
      - kafka
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      SCHEMA_REGISTRY: http://registry:8081
      DISPLAY: ${DOCKER_DISPLAY}
    volumes:
      - ./scripts:/scripts
    entrypoint: bash
    networks:
      - graphnet
  
  
  timer:
    image: slominskir/shelved-timer:1.1.0
    hostname: timer
    container_name: timer
    depends_on:
      - zookeeper
      - kafka
      - registry
      - console
    environment:
      BOOTSTRAP_SERVERS: "kafka:9092"
      SCHEMA_REGISTRY: "http://registry:8081"
   
    networks:
      - graphnet